// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7k6jX1NhPYqjo-XYqr7Lsm6IZcbUgS_U',
    appId: '1:884093265220:web:ec61b9c0ee9a391ba42311',
    messagingSenderId: '884093265220',
    projectId: 'flutter-course-ow',
    authDomain: 'flutter-course-ow.firebaseapp.com',
    storageBucket: 'flutter-course-ow.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6lJhVhu9IP2VN9P0o3EgV1Z707HnEK7g',
    appId: '1:884093265220:android:124c5eaba8349b39a42311',
    messagingSenderId: '884093265220',
    projectId: 'flutter-course-ow',
    storageBucket: 'flutter-course-ow.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAf4Jgs_K9FeV1WlRxch725OrH5Ak4CcYY',
    appId: '1:884093265220:ios:1a0752e9ce5fc8c8a42311',
    messagingSenderId: '884093265220',
    projectId: 'flutter-course-ow',
    storageBucket: 'flutter-course-ow.appspot.com',
    androidClientId: '884093265220-v50hlngr743lrcp0n8fp6iq01c17a5ar.apps.googleusercontent.com',
    iosClientId: '884093265220-frgcfp0h47ih8qh4gulogq9b7233a7rt.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase',
  );
}
